[theme]
primaryColor = "#127C80"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F6F6"
textColor = "#172D37"
font = "sans-serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
